# Generated by Django 5.0.1 on 2024-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("department", models.CharField(max_length=100)),
                ("date_of_employment", models.DateField()),
                ("city_of_residence", models.CharField(max_length=100)),
                ("overtime_hours", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
